### ISSUE TITLE
Gml QGIS Stylesheets

### ISSUE THREAD

**Issue by onplot** [OrdnanceSurvey/OS-Open-Roads-stylesheets#3]
When loading into QGIS 3.12.1 I get "unexpected character at line 53 column 69" for all four .qml files.  I have also downloaded the Gpkg version of the data and the requisite .qml files and the same happens with those
![OS Open Roads_StyleError](https://user-images.githubusercontent.com/22997180/78694597-d179df80-78f4-11ea-8db1-9714d724672a.png)

**Comment by egil1978** [comment]
Hi, this is a strange one. I have tried replicating this in QGIS 3.14 but both the GML and GPKG load in fine and the accompanying QML files load also? Have you tried another version of QGIS?
